CREATE TABLE IF NOT EXISTS USUARIO (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	ativo BOOLEAN DEFAULT TRUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	senha VARCHAR(255) NOT NULL,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Tarefas (
	id SERIAL PRIMARY KEY,
	titulo VARCHAR(255) NOT NULL,
	descricao VARCHAR(255) NOT NULL,
	usuario_id INTEGER NOT NULL REFERENCES USUARIO(id) ON DELETE CASCADE        
);
